# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Joy
tagline:          'A Jekyll theme'
description:      'Blogposts about CS, Math, Finance, Economics and more'
# url:              http://hyde.getpoole.com
baseurl:          ''

author:
  name:           ''
  url:            https://eternalbujoyy.github.io/


gems:                [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/eternaljoyy
